version = 0.1


# UK config

[live-uk.deploy.parameters]
stack_name = "newswatch-live"
resolve_s3 = true
s3_prefix = "newswatch-live"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
  "Env=live-uk",
]

[dev-uk.deploy.parameters]
stack_name = "newswatch-dev"
resolve_s3 = true
s3_prefix = "newswatch-dev"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
  "Env=dev-uk",
]


# US config

[live-us.deploy.parameters]
stack_name = "newswatch-dev-us"
resolve_s3 = true
s3_prefix = "newswatch-live"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
  "Env=live-us",
]

[dev-us.deploy.parameters]
stack_name = "newswatch-dev-us"
resolve_s3 = true
s3_prefix = "newswatch-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
  "Env=dev-us",
]
