
name: Deploy Live
run-name: '${{ github.workflow }}'

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy-live-uk:
    uses: ./.github/workflows/deploy.yaml
    with:
      target-env: live-uk
    secrets: inherit
  deploy-live-us:
    uses: ./.github/workflows/deploy.yaml
    with:
      target-env: live-us
    secrets: inherit
