
name: Deploy Live
run-name: '${{ github.workflow }}'

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yaml
    with:
      target-env: live
    secrets: inherit
