
name: Deploy Dev
run-name: '${{ github.workflow }}'

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev-uk:
    uses: ./.github/workflows/deploy.yaml
    with:
      target-env: dev-uk
    secrets: inherit
  deploy-dev-us:
    uses: ./.github/workflows/deploy.yaml
    with:
      target-env: dev-us
    secrets: inherit
