name: Terraform Plan

on:
  [workflow_dispatch, push]

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_NEWSWATCH_S3_BUCKET: ${{ secrets.TF_VAR_NEWSWATCH_S3_BUCKET }}
  TERRAFORM_NEWSWATCH_S3_BUCKET: ${{ secrets.TERRAFORM_NEWSWATCH_S3_BUCKET }}
  TERRAFORM_NEWSWATCH_DYAMODB_TABLE: ${{ secrets.TERRAFORM_NEWSWATCH_DYAMODB_TABLE }}

jobs:
  terraform-plan:
    name: terraform-plan
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/terraform_newswatch_role
          aws-region: eu-west-1

      - name: Terraform init
        run: make tf-init

      - name: Terraform plan
        run: make tf-plan
