name: Test
run-name: '${{ github.workflow }}'

on: [push]

jobs:
  code-quality-and-tests:
    name: code-quality-and-tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Install dependencies
        run: make deps

      - name: Run pre-commit hooks
        run: make pc

      - name: Run tests
        run: make test

      - name: Validate SAM template
        run: make sv
