name: Test
run-name: '${{ github.workflow }}'

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  code-quality-and-tests:
    name: code-quality-and-tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.7"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: Install python dependencies
        run: make setup-ci

      - name: Run pre-commit hooks
        run: make lint

      - name: Run tests
        run: make test-cov | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Validate SAM template
        run: make validate
